version: '3'

services:
  
  chat:
    container_name: chat_node
    user: 1000:1000
    build:
      context: .
      dockerfile: ./_docker/app/Dockerfile
    volumes:
      - "./:/var/www/chat"
    ports:
      - "3000:3000"
      - "3005:3005"