version: '3'

networks:
  app:

services:  

  server:
    tty: true
    container_name: server_chat
    user: 1000:1000
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./_docker/Dockerfile.server.dev
    volumes:
      - "./server/:/var/www/server"
    ports:
      - "3000:3000"
    networks:
      - app

  front:
    tty: true
    container_name: front_chat
    user: 1000:1000
    depends_on:
      - server
    build:
      context: .
      dockerfile: ./_docker/Dockerfile.front.dev
    volumes:
      - "./front/:/var/www/app"
    ports:
      - "80:80"
    networks:
      - app

  db:
    container_name: db_chat
    image: mongo:5.0.15
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - app

  db_viewer:
    container_name: db_viewer_chat
    depends_on:
      - db
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://admin:root@db:27017/
    networks:
      - app
  

  